"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-development-secret-key"
)

DEBUG = os.environ.get(
    "DEBUG",
    "False"
).lower() == "true"

# Explicitly allow domain variations
ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "web-production-f2684.up.railway.app",
    "mjm.up.railway.app",
]

# Trust the secure origins for incoming forms
CSRF_TRUSTED_ORIGINS = [
    "https://web-production-f2684.up.railway.app",
    "https://mjm.up.railway.app",
]

# Tell Django your app runs behind Railway's reverse proxy header
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Prevent strict crashes during asset manifestation lookups
WHITENOISE_MANIFEST_STRICT = False

# Application definition
INSTALLED_APPS = [
    'cloudinary_storage',  # Cloudinary must initialize before staticfiles engine handles lookups
    'cloudinary',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'projects',
    'contact',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Commented out temporarily to avoid 500 crashes if file does not exist yet:
                # "core.context_processors.profile_context",
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Cloudinary credentials configuration
# config/settings.py

# Double-lookup ensures that whichever way you named it on Railway, Django captures it!
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME') or os.environ.get('CLOUD_NAME'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY') or os.environ.get('API_KEY'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET') or os.environ.get('API_SECRET'),
}


# Unified storage routing block for Django 5.x
STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# Fallback parameter required by the out-of-date 'cloudinary_storage' module
# This specifically satisfies its legacy collectstatic verification hooks
STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"

# Database routing configuration
DATABASE_URL = os.environ.get("DATABASE_URL")

if DATABASE_URL:
    import dj_database_url
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Assets distribution configuration
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
